export const CLASS_META_PROPERTY_KEY = 'META';
export const ROUTER_LINK_META_PROPERTY_KEY_PREFIX = 'ROUTER_LINK:';
export const STATIC_LINK_META_PROPERTY_KEY_PREFIX = 'STATIC_LINK:';
export const ENDPOINT_META_PROPERTY_KEY_PREFIX = 'ENDPOINT:';